### ISSUE TITLE
SEO description

### ISSUE THREAD

**Issue by thiborose** [psawa/gecko-app#19]
When the website appears in google, the description provided is the description of Eduardo's profile. It should show the decription of the application itself (about section)

![image](https://user-images.githubusercontent.com/38402230/103458763-76eaa400-4d0b-11eb-8d19-7b829ee5513d.png)

**Comment by Eduardo-Calo** [comment]
we can update the intro with "GECko+ is more than a Grammatical Error Corrector. It is a writing assistant tool for English, which corrects spelling, grammatical, and discourse mistakes in your texts.", and select it as SEO description.

**Comment by Eduardo-Calo** [comment]
Description updated. However, now the SEO description has changed. Furthermore, we need to suppress somehow this old link since the new one is never found.

<img width="736" alt="Immagine 2021-01-09 013559" src="https://user-images.githubusercontent.com/57707528/104077688-1089e800-521b-11eb-84c7-e417e258a0ef.png">

**Comment by thiborose** [comment]
I'll see what I can do for the outdated google results.
